import Header from "./components/Header";
import ShowSongs from "./features/ShowSongs";
import NewTest from "./features/NewTest";
import ChangeNumber from "./features/ChangeNumber";
import TodoListVersion1 from "./features/TodoListVersion1";
import { useState } from "react";
import UseEffectFeature from "./features/UseEffect";

const userdata = [
  {
    id: 1,
    fullname: "Nguyen Van Nam",
    age: 22,
    gender: "male",
  },
  {
    id: 2,
    fullname: "Nguyen Thi Tuyet",
    age: 18,
    gender: "female",
  },
  {
    id: 3,
    fullname: "Nguyen Van Nam",
    age: 42,
    gender: "male",
  },
  {
    id: 4,
    fullname: "Nguyen Thi Tuyet",
    age: 16,
    gender: "female",
  },
];

const newData = [
  {
    id: 1,
    first_name: "Erna",
    last_name: "Golden of Ireland",
    email: "egoldenofireland0@nytimes.com",
    gender: "Female",
    Country: "China",
    City: "Junliangcheng",
    Age: 147,
  },
  {
    id: 2,
    first_name: "Mabel",
    last_name: "Umbers",
    email: "mumbers1@hao123.com",
    gender: "Male",
    Country: "Sao Tome and Principe",
    City: "São Tomé",
    Age: 107,
  },
  {
    id: 3,
    first_name: "Gordie",
    last_name: "Lankford",
    email: "glankford2@woothemes.com",
    gender: "Female",
    Country: "China",
    City: "Shuanghe",
    Age: 17,
  },
  {
    id: 4,
    first_name: "Reggis",
    last_name: "Henniger",
    email: "rhenniger3@harvard.edu",
    gender: "Male",
    Country: "Russia",
    City: "Ugra",
    Age: 138,
  },
  {
    id: 5,
    first_name: "Mason",
    last_name: "Morkham",
    email: "mmorkham4@sciencedaily.com",
    gender: "Male",
    Country: "Poland",
    City: "Rokietnica",
    Age: 135,
  },
  {
    id: 6,
    first_name: "Myrvyn",
    last_name: "Stickells",
    email: "mstickells5@yellowpages.com",
    gender: "Female",
    Country: "China",
    City: "Gaoqiao",
    Age: 109,
  },
  {
    id: 7,
    first_name: "Thatch",
    last_name: "Sodeau",
    email: "tsodeau6@uiuc.edu",
    gender: "Male",
    Country: "Philippines",
    City: "Buliran Segundo",
    Age: 87,
  },
  {
    id: 8,
    first_name: "Gavin",
    last_name: "Baxstar",
    email: "gbaxstar7@smh.com.au",
    gender: "Male",
    Country: "United States",
    City: "Carson City",
    Age: 118,
  },
  {
    id: 9,
    first_name: "Sophronia",
    last_name: "Pither",
    email: "spither8@fema.gov",
    gender: "Female",
    Country: "China",
    City: "Xiapu",
    Age: 63,
  },
  {
    id: 10,
    first_name: "Keely",
    last_name: "Ladewig",
    email: "kladewig9@timesonline.co.uk",
    gender: "Male",
    Country: "Argentina",
    City: "Barranqueras",
    Age: 79,
  },
  {
    id: 11,
    first_name: "Pincas",
    last_name: "Drakes",
    email: "pdrakesa@who.int",
    gender: "Male",
    Country: "Mexico",
    City: "Benito Juarez",
    Age: 102,
  },
  {
    id: 12,
    first_name: "Rebekkah",
    last_name: "Padbery",
    email: "rpadberyb@jigsy.com",
    gender: "Male",
    Country: "Brazil",
    City: "Recife",
    Age: 59,
  },
  {
    id: 13,
    first_name: "Donalt",
    last_name: "Filippucci",
    email: "dfilippuccic@jigsy.com",
    gender: "Male",
    Country: "Russia",
    City: "Vostok",
    Age: 149,
  },
  {
    id: 14,
    first_name: "Toma",
    last_name: "Vigar",
    email: "tvigard@cloudflare.com",
    gender: "Female",
    Country: "Canada",
    City: "Nakusp",
    Age: 26,
  },
  {
    id: 15,
    first_name: "Gnni",
    last_name: "Duckfield",
    email: "gduckfielde@usgs.gov",
    gender: "Female",
    Country: "Indonesia",
    City: "Cihaur",
    Age: 40,
  },
  {
    id: 16,
    first_name: "Tammie",
    last_name: "Renals",
    email: "trenalsf@wikia.com",
    gender: "Female",
    Country: "China",
    City: "Guanzhuang",
    Age: 97,
  },
  {
    id: 17,
    first_name: "Cyrus",
    last_name: "Lampaert",
    email: "clampaertg@oracle.com",
    gender: "Female",
    Country: "Russia",
    City: "Sut-Khol’",
    Age: 81,
  },
  {
    id: 18,
    first_name: "Katerine",
    last_name: "Dingivan",
    email: "kdingivanh@xrea.com",
    gender: "Female",
    Country: "Liberia",
    City: "Gbarnga",
    Age: 142,
  },
  {
    id: 19,
    first_name: "Joeann",
    last_name: "Rodenborch",
    email: "jrodenborchi@nymag.com",
    gender: "Non-binary",
    Country: "Yemen",
    City: "Al Tuḩaytā’",
    Age: 121,
  },
  {
    id: 20,
    first_name: "Noelani",
    last_name: "Pashba",
    email: "npashbaj@hc360.com",
    gender: "Female",
    Country: "Brazil",
    City: "Águas de Lindóia",
    Age: 124,
  },
  {
    id: 21,
    first_name: "Marty",
    last_name: "Pitchers",
    email: "mpitchersk@mysql.com",
    gender: "Male",
    Country: "China",
    City: "Sizao",
    Age: 15,
  },
  {
    id: 22,
    first_name: "Lydon",
    last_name: "Pirozzi",
    email: "lpirozzil@ebay.com",
    gender: "Female",
    Country: "Latvia",
    City: "Kocēni",
    Age: 97,
  },
  {
    id: 23,
    first_name: "Maurene",
    last_name: "Reary",
    email: "mrearym@t-online.de",
    gender: "Female",
    Country: "China",
    City: "Shangsanji",
    Age: 112,
  },
  {
    id: 24,
    first_name: "Hersh",
    last_name: "Pulfer",
    email: "hpulfern@intel.com",
    gender: "Female",
    Country: "Thailand",
    City: "Bang Rakam",
    Age: 83,
  },
  {
    id: 25,
    first_name: "Madalyn",
    last_name: "Winfrey",
    email: "mwinfreyo@ihg.com",
    gender: "Male",
    Country: "Thailand",
    City: "Si Mahosot",
    Age: 41,
  },
  {
    id: 26,
    first_name: "Debby",
    last_name: "Bennen",
    email: "dbennenp@icio.us",
    gender: "Female",
    Country: "China",
    City: "Huancheng",
    Age: 145,
  },
  {
    id: 27,
    first_name: "Sebastian",
    last_name: "Cowper",
    email: "scowperq@hibu.com",
    gender: "Male",
    Country: "Russia",
    City: "Valuyki",
    Age: 62,
  },
  {
    id: 28,
    first_name: "Lida",
    last_name: "Hammarberg",
    email: "lhammarbergr@reverbnation.com",
    gender: "Female",
    Country: "China",
    City: "Renyi",
    Age: 32,
  },
  {
    id: 29,
    first_name: "Maurine",
    last_name: "Achurch",
    email: "machurchs@sohu.com",
    gender: "Female",
    Country: "Poland",
    City: "Chełm",
    Age: 117,
  },
  {
    id: 30,
    first_name: "Dev",
    last_name: "Karolowski",
    email: "dkarolowskit@amazonaws.com",
    gender: "Agender",
    Country: "Indonesia",
    City: "Cibeunying",
    Age: 42,
  },
  {
    id: 31,
    first_name: "Bruce",
    last_name: "Hancorn",
    email: "bhancornu@icq.com",
    gender: "Male",
    Country: "Mexico",
    City: "Buenavista",
    Age: 84,
  },
  {
    id: 32,
    first_name: "Cyndia",
    last_name: "Anwell",
    email: "canwellv@pbs.org",
    gender: "Female",
    Country: "Syria",
    City: "Sarāqib",
    Age: 77,
  },
  {
    id: 33,
    first_name: "Ahmad",
    last_name: "Stelle",
    email: "astellew@kickstarter.com",
    gender: "Female",
    Country: "Bangladesh",
    City: "Rāipur",
    Age: 135,
  },
  {
    id: 34,
    first_name: "Gypsy",
    last_name: "Surgeoner",
    email: "gsurgeonerx@va.gov",
    gender: "Female",
    Country: "China",
    City: "Kanshan",
    Age: 94,
  },
  {
    id: 35,
    first_name: "Dev",
    last_name: "Jelphs",
    email: "djelphsy@artisteer.com",
    gender: "Female",
    Country: "Japan",
    City: "Ōkuchi",
    Age: 18,
  },
  {
    id: 36,
    first_name: "Kinnie",
    last_name: "Luigi",
    email: "kluigiz@google.com",
    gender: "Male",
    Country: "Colombia",
    City: "El Tambo",
    Age: 119,
  },
  {
    id: 37,
    first_name: "Skell",
    last_name: "Orman",
    email: "sorman10@wunderground.com",
    gender: "Male",
    Country: "Poland",
    City: "Mełgiew",
    Age: 133,
  },
  {
    id: 38,
    first_name: "Kev",
    last_name: "Atterbury",
    email: "katterbury11@about.com",
    gender: "Male",
    Country: "Peru",
    City: "Ucuncha",
    Age: 51,
  },
  {
    id: 39,
    first_name: "Kathleen",
    last_name: "Horick",
    email: "khorick12@pcworld.com",
    gender: "Male",
    Country: "Morocco",
    City: "Talzemt",
    Age: 44,
  },
  {
    id: 40,
    first_name: "Dorree",
    last_name: "Lamp",
    email: "dlamp13@taobao.com",
    gender: "Genderfluid",
    Country: "China",
    City: "Yanglin",
    Age: 58,
  },
  {
    id: 41,
    first_name: "Jackson",
    last_name: "Lindop",
    email: "jlindop14@freewebs.com",
    gender: "Male",
    Country: "South Korea",
    City: "Taisen-ri",
    Age: 98,
  },
  {
    id: 42,
    first_name: "Denyse",
    last_name: "Gyorgy",
    email: "dgyorgy15@unicef.org",
    gender: "Genderqueer",
    Country: "Brazil",
    City: "Santa Gertrudes",
    Age: 24,
  },
  {
    id: 43,
    first_name: "Myrta",
    last_name: "Beach",
    email: "mbeach16@ed.gov",
    gender: "Male",
    Country: "Indonesia",
    City: "Kaliterus",
    Age: 68,
  },
  {
    id: 44,
    first_name: "Fayina",
    last_name: "Trippick",
    email: "ftrippick17@independent.co.uk",
    gender: "Female",
    Country: "Indonesia",
    City: "Setanggor",
    Age: 108,
  },
  {
    id: 45,
    first_name: "Fiorenze",
    last_name: "McVanamy",
    email: "fmcvanamy18@hostgator.com",
    gender: "Female",
    Country: "Philippines",
    City: "Carmen",
    Age: 51,
  },
  {
    id: 46,
    first_name: "Glad",
    last_name: "Dunnet",
    email: "gdunnet19@live.com",
    gender: "Female",
    Country: "Ecuador",
    City: "Ambato",
    Age: 13,
  },
  {
    id: 47,
    first_name: "Luca",
    last_name: "Di Batista",
    email: "ldibatista1a@amazon.co.jp",
    gender: "Female",
    Country: "Canada",
    City: "Dieppe",
    Age: 68,
  },
  {
    id: 48,
    first_name: "Barbaraanne",
    last_name: "Allerton",
    email: "ballerton1b@bloglovin.com",
    gender: "Female",
    Country: "Nicaragua",
    City: "Belén",
    Age: 129,
  },
  {
    id: 49,
    first_name: "Antony",
    last_name: "Marie",
    email: "amarie1c@uiuc.edu",
    gender: "Male",
    Country: "United States",
    City: "Racine",
    Age: 33,
  },
  {
    id: 50,
    first_name: "Billi",
    last_name: "Kirgan",
    email: "bkirgan1d@house.gov",
    gender: "Female",
    Country: "China",
    City: "Zhonghouhe",
    Age: 80,
  },
  {
    id: 51,
    first_name: "Artie",
    last_name: "Clayworth",
    email: "aclayworth1e@pbs.org",
    gender: "Female",
    Country: "Armenia",
    City: "Tsiatsan",
    Age: 26,
  },
  {
    id: 52,
    first_name: "Karel",
    last_name: "Robertelli",
    email: "krobertelli1f@narod.ru",
    gender: "Male",
    Country: "Kyrgyzstan",
    City: "Ivanovo-Alekseyevka",
    Age: 132,
  },
  {
    id: 53,
    first_name: "Shena",
    last_name: "Bithany",
    email: "sbithany1g@networkadvertising.org",
    gender: "Male",
    Country: "Mexico",
    City: "Buenos Aires",
    Age: 138,
  },
  {
    id: 54,
    first_name: "Nilson",
    last_name: "Mewitt",
    email: "nmewitt1h@woothemes.com",
    gender: "Female",
    Country: "France",
    City: "Mitry-Mory",
    Age: 51,
  },
  {
    id: 55,
    first_name: "Uri",
    last_name: "Dovidian",
    email: "udovidian1i@npr.org",
    gender: "Genderqueer",
    Country: "China",
    City: "Xiangshui",
    Age: 48,
  },
  {
    id: 56,
    first_name: "Vale",
    last_name: "Yezafovich",
    email: "vyezafovich1j@whitehouse.gov",
    gender: "Female",
    Country: "Brazil",
    City: "Jaguariúna",
    Age: 78,
  },
  {
    id: 57,
    first_name: "Bronny",
    last_name: "Sutehall",
    email: "bsutehall1k@geocities.com",
    gender: "Male",
    Country: "Brazil",
    City: "Barra de São Francisco",
    Age: 77,
  },
  {
    id: 58,
    first_name: "Fabe",
    last_name: "Menezes",
    email: "fmenezes1l@ted.com",
    gender: "Female",
    Country: "Macedonia",
    City: "Јегуновце",
    Age: 81,
  },
  {
    id: 59,
    first_name: "Katha",
    last_name: "Cleeve",
    email: "kcleeve1m@skype.com",
    gender: "Female",
    Country: "Mongolia",
    City: "Buyant",
    Age: 120,
  },
  {
    id: 60,
    first_name: "Zachery",
    last_name: "D'Onisi",
    email: "zdonisi1n@hibu.com",
    gender: "Male",
    Country: "Afghanistan",
    City: "Shahrak",
    Age: 27,
  },
];

const phone = {
  phoneName: "I phone 13",
  price: "1200 USD",
  brand: "Apple",
};

const zingMp3Data = [
  {
    albumId: 1,
    id: 1,
    title: "Túp lều vàng",
    url: "https://via.placeholder.com/600/92c952",
    thumbnailUrl:
      "https://photo-resize-zmp3.zadn.vn/w240_r16x9_jpeg/thumb_video/d/6/e/6/d6e6201323fed8fb16886a3f428fc4f7.jpg",
  },
  {
    albumId: 1,
    id: 2,
    title: "Túp lều vàng",
    url: "https://via.placeholder.com/600/771796",
    thumbnailUrl:
      "https://photo-resize-zmp3.zadn.vn/w240_r16x9_jpeg/thumb_video/d/6/e/6/d6e6201323fed8fb16886a3f428fc4f7.jpg",
  },
  {
    albumId: 1,
    id: 3,
    title: "Túp lều vàng",
    url: "https://via.placeholder.com/600/24f355",
    thumbnailUrl:
      "https://photo-resize-zmp3.zadn.vn/w240_r16x9_jpeg/thumb_video/d/6/e/6/d6e6201323fed8fb16886a3f428fc4f7.jpg",
  },
  {
    albumId: 1,
    id: 4,
    title: "Túp lều vàng",
    url: "https://via.placeholder.com/600/d32776",
    thumbnailUrl:
      "https://photo-resize-zmp3.zadn.vn/w240_r16x9_jpeg/thumb_video/d/6/e/6/d6e6201323fed8fb16886a3f428fc4f7.jpg",
  },
  {
    albumId: 1,
    id: 5,
    title: "natus nisi omnis corporis facere molestiae rerum in",
    url: "https://via.placeholder.com/600/f66b97",
    thumbnailUrl:
      "https://photo-resize-zmp3.zadn.vn/w240_r16x9_jpeg/thumb_video/6/8/9/b/689b9f49c7ceb4ca4dc326571bba4e2a.jpg",
  },
  {
    albumId: 1,
    id: 6,
    title: "accusamus ea aliquid et amet sequi nemo",
    url: "https://via.placeholder.com/600/56a8c2",
    thumbnailUrl:
      "https://photo-resize-zmp3.zadn.vn/w240_r16x9_jpeg/thumb_video/6/8/9/b/689b9f49c7ceb4ca4dc326571bba4e2a.jpg",
  },
  {
    albumId: 1,
    id: 7,
    title: "officia delectus consequatur vero aut veniam explicabo molestias",
    url: "https://via.placeholder.com/600/b0f7cc",
    thumbnailUrl:
      "https://photo-resize-zmp3.zadn.vn/w240_r16x9_jpeg/thumb_video/6/8/9/b/689b9f49c7ceb4ca4dc326571bba4e2a.jpg",
  },
  {
    albumId: 1,
    id: 8,
    title: "aut porro officiis laborum odit ea laudantium corporis",
    url: "https://via.placeholder.com/600/54176f",
    thumbnailUrl:
      "https://photo-resize-zmp3.zadn.vn/w240_r16x9_jpeg/thumb_video/6/8/9/b/689b9f49c7ceb4ca4dc326571bba4e2a.jpg",
  },
  {
    albumId: 1,
    id: 9,
    title: "qui eius qui autem sed",
    url: "https://via.placeholder.com/600/51aa97",
    thumbnailUrl1:
      "https://photo-resize-zmp3.zadn.vn/w240_r16x9_jpeg/thumb_video/4/7/7/5/47755662b9802742229217de267b24fe.jpg",
  },
  {
    albumId: 1,
    id: 10,
    title: "beatae et provident et ut vel",
    url: "https://via.placeholder.com/600/810b14",
    thumbnailUrl:
      "https://photo-resize-zmp3.zadn.vn/w240_r16x9_jpeg/thumb_video/4/d/b/f/4dbf769079e956c3d104130af83ae2c5.jpg",
  },
  {
    albumId: 1,
    id: 11,
    title: "nihil at amet non hic quia qui",
    url: "https://via.placeholder.com/600/1ee8a4",
    thumbnailUrl1:
      "https://photo-resize-zmp3.zadn.vn/w240_r16x9_jpeg/thumb_video/4/7/7/5/47755662b9802742229217de267b24fe.jpg",
  },
  {
    albumId: 1,
    id: 12,
    title:
      "mollitia soluta ut rerum eos aliquam consequatur perspiciatis maiores",
    url: "https://via.placeholder.com/600/66b7d2",
    thumbnailUrl:
      "https://photo-resize-zmp3.zadn.vn/w240_r16x9_jpeg/thumb_video/4/d/b/f/4dbf769079e956c3d104130af83ae2c5.jpg",
  },
  {
    albumId: 1,
    id: 13,
    title: "repudiandae iusto deleniti rerum",
    url: "https://via.placeholder.com/600/197d29",
    thumbnailUrl1:
      "https://photo-resize-zmp3.zadn.vn/w240_r16x9_jpeg/thumb_video/4/7/7/5/47755662b9802742229217de267b24fe.jpg",
  },
  {
    albumId: 1,
    id: 14,
    title: "est necessitatibus architecto ut laborum",
    url: "https://via.placeholder.com/600/61a65",
    thumbnailUrl:
      "https://photo-resize-zmp3.zadn.vn/w240_r16x9_jpeg/thumb_video/4/d/b/f/4dbf769079e956c3d104130af83ae2c5.jpg",
  },
  {
    albumId: 1,
    id: 15,
    title: "harum dicta similique quis dolore earum ex qui",
    url: "https://via.placeholder.com/600/f9cee5",
    thumbnailUrl:
      "https://photo-resize-zmp3.zadn.vn/w240_r16x9_jpeg/thumb_video/4/d/b/f/4dbf769079e956c3d104130af83ae2c5.jpg",
  },
  {
    albumId: 1,
    id: 16,
    title: "iusto sunt nobis quasi veritatis quas expedita voluptatum deserunt",
    url: "https://via.placeholder.com/600/fdf73e",
    thumbnailUrl1:
      "https://photo-resize-zmp3.zadn.vn/w240_r16x9_jpeg/thumb_video/4/7/7/5/47755662b9802742229217de267b24fe.jpg",
  },
  {
    albumId: 1,
    id: 17,
    title: "natus doloribus necessitatibus ipsa",
    url: "https://via.placeholder.com/600/9c184f",
    thumbnailUrl:
      "https://photo-resize-zmp3.zadn.vn/w240_r16x9_jpeg/thumb_video/4/d/b/f/4dbf769079e956c3d104130af83ae2c5.jpg",
  },
  {
    albumId: 1,
    id: 18,
    title: "laboriosam odit nam necessitatibus et illum dolores reiciendis",
    url: "https://via.placeholder.com/600/1fe46f",
    thumbnailUrl1:
      "https://photo-resize-zmp3.zadn.vn/w240_r16x9_jpeg/thumb_video/4/7/7/5/47755662b9802742229217de267b24fe.jpg",
  },
  {
    albumId: 1,
    id: 19,
    title: "perferendis nesciunt eveniet et optio a",
    url: "https://via.placeholder.com/600/56acb2",
    thumbnailUrl:
      "https://photo-resize-zmp3.zadn.vn/w240_r16x9_jpeg/thumb_video/4/d/b/f/4dbf769079e956c3d104130af83ae2c5.jpg",
  },
  {
    albumId: 1,
    id: 20,
    title:
      "assumenda voluptatem laboriosam enim consequatur veniam placeat reiciendis error",
    url: "https://via.placeholder.com/600/8985dc",
    thumbnailUrl: "https://via.placeholder.com/150/8985dc",
  },
  {
    albumId: 1,
    id: 21,
    title: "ad et natus qui",
    url: "https://via.placeholder.com/600/5e12c6",
    thumbnailUrl: "https://via.placeholder.com/150/5e12c6",
  },
  {
    albumId: 1,
    id: 22,
    title: "et ea illo et sit voluptas animi blanditiis porro",
    url: "https://via.placeholder.com/600/45601a",
    thumbnailUrl: "https://via.placeholder.com/150/45601a",
  },
  {
    albumId: 1,
    id: 23,
    title: "harum velit vero totam",
    url: "https://via.placeholder.com/600/e924e6",
    thumbnailUrl: "https://via.placeholder.com/150/e924e6",
  },
  {
    albumId: 1,
    id: 24,
    title: "beatae officiis ut aut",
    url: "https://via.placeholder.com/600/8f209a",
    thumbnailUrl: "https://via.placeholder.com/150/8f209a",
  },
  {
    albumId: 1,
    id: 25,
    title: "facere non quis fuga fugit vitae",
    url: "https://via.placeholder.com/600/5e3a73",
    thumbnailUrl1:
      "https://photo-resize-zmp3.zadn.vn/w240_r16x9_jpeg/thumb_video/4/7/7/5/47755662b9802742229217de267b24fe.jpg",
  },
  {
    albumId: 1,
    id: 26,
    title: "asperiores nobis voluptate qui",
    url: "https://via.placeholder.com/600/474645",
    thumbnailUrl: "https://via.placeholder.com/150/474645",
  },
  {
    albumId: 1,
    id: 27,
    title: "sit asperiores est quos quis nisi veniam error",
    url: "https://via.placeholder.com/600/c984bf",
    thumbnailUrl: "https://via.placeholder.com/150/c984bf",
  },
  {
    albumId: 1,
    id: 28,
    title: "non neque eligendi molestiae repudiandae illum voluptatem qui aut",
    url: "https://via.placeholder.com/600/392537",
    thumbnailUrl1:
      "https://photo-resize-zmp3.zadn.vn/w240_r16x9_jpeg/thumb_video/4/7/7/5/47755662b9802742229217de267b24fe.jpg",
  },
  {
    albumId: 1,
    id: 29,
    title: "aut ipsam quos ab placeat omnis",
    url: "https://via.placeholder.com/600/602b9e",
    thumbnailUrl: "https://via.placeholder.com/150/602b9e",
  },
  {
    albumId: 1,
    id: 30,
    title: "odio enim voluptatem quidem aut nihil illum",
    url: "https://via.placeholder.com/600/372c93",
    thumbnailUrl: "https://via.placeholder.com/150/372c93",
  },
  {
    albumId: 1,
    id: 31,
    title: "voluptate voluptates sequi",
    url: "https://via.placeholder.com/600/a7c272",
    thumbnailUrl: "https://via.placeholder.com/150/a7c272",
  },
  {
    albumId: 1,
    id: 32,
    title: "ad enim dignissimos voluptatem similique",
    url: "https://via.placeholder.com/600/c70a4d",
    thumbnailUrl: "https://via.placeholder.com/150/c70a4d",
  },
  {
    albumId: 1,
    id: 33,
    title: "culpa ipsam nobis qui fuga magni et mollitia",
    url: "https://via.placeholder.com/600/501fe1",
    thumbnailUrl: "https://via.placeholder.com/150/501fe1",
  },
  {
    albumId: 1,
    id: 34,
    title: "vitae est facere quia itaque adipisci perferendis id maiores",
    url: "https://via.placeholder.com/600/35185e",
    thumbnailUrl: "https://via.placeholder.com/150/35185e",
  },
  {
    albumId: 1,
    id: 35,
    title: "tenetur minus voluptatum et",
    url: "https://via.placeholder.com/600/c96cad",
    thumbnailUrl: "https://via.placeholder.com/150/c96cad",
  },
  {
    albumId: 1,
    id: 36,
    title: "expedita rerum eaque",
    url: "https://via.placeholder.com/600/4d564d",
    thumbnailUrl: "https://via.placeholder.com/150/4d564d",
  },
  {
    albumId: 1,
    id: 37,
    title: "totam voluptas iusto deserunt dolores",
    url: "https://via.placeholder.com/600/ea51da",
    thumbnailUrl: "https://via.placeholder.com/150/ea51da",
  },
  {
    albumId: 1,
    id: 38,
    title: "natus magnam iure rerum pariatur molestias dolore nisi",
    url: "https://via.placeholder.com/600/4f5b8d",
    thumbnailUrl: "https://via.placeholder.com/150/4f5b8d",
  },
  {
    albumId: 1,
    id: 39,
    title: "molestiae nam ullam et rerum doloribus",
    url: "https://via.placeholder.com/600/1e71a2",
    thumbnailUrl: "https://via.placeholder.com/150/1e71a2",
  },
  {
    albumId: 1,
    id: 40,
    title: "est quas voluptates dignissimos sint praesentium nisi recusandae",
    url: "https://via.placeholder.com/600/3a0b95",
    thumbnailUrl: "https://via.placeholder.com/150/3a0b95",
  },
  {
    albumId: 1,
    id: 41,
    title: "in voluptatem doloremque cum atque architecto deleniti",
    url: "https://via.placeholder.com/600/659403",
    thumbnailUrl: "https://via.placeholder.com/150/659403",
  },
  {
    albumId: 1,
    id: 42,
    title: "voluptatibus a autem molestias voluptas architecto culpa",
    url: "https://via.placeholder.com/600/ca50ac",
    thumbnailUrl: "https://via.placeholder.com/150/ca50ac",
  },
  {
    albumId: 1,
    id: 43,
    title: "eius hic autem ad beatae voluptas",
    url: "https://via.placeholder.com/600/6ad437",
    thumbnailUrl: "https://via.placeholder.com/150/6ad437",
  },
  {
    albumId: 1,
    id: 44,
    title: "neque eum provident et inventore sed ipsam dignissimos quo",
    url: "https://via.placeholder.com/600/29fe9f",
    thumbnailUrl: "https://via.placeholder.com/150/29fe9f",
  },
];

const zingMp3Data2 = [
  {
    id: 1,
    img: "https://photo-resize-zmp3.zadn.vn/w320_r1x1_webp/cover/0/a/9/9/0a99ffcb94e715f0ea25e5be651dbbe5.jpg",
    name: "Nhạc Xuân Hay Nhất",
    description: "Đón chào mùa xuân an lành cùng những...",
  },
  {
    id: 2,
    img: "https://photo-resize-zmp3.zadn.vn/w320_r1x1_webp/cover/d/b/f/e/dbfec1b629a8187fecdcc400f48fbad0.jpg",
    name: "Tết Remake",
    description: "Nhạc tết thay áo khi được làm mới lại",
  },
  {
    id: 3,
    img: "https://photo-resize-zmp3.zadn.vn/w320_r1x1_webp/cover/3/f/4/3/3f439e1f0a1ad3de42187428f3ab94ad.jpg",
    name: "Đón xuân nhẹ nhàng",
    description: "Dành cho những phút giây nhẹ nhàng...",
  },
  {
    id: 4,
    img: "https://photo-resize-zmp3.zadn.vn/w320_r1x1_webp/cover/0/0/e/8/00e8eba0861abeaa4b4674c338c440b5.jpg",
    name: "Nhạc xuân remix",
    description: "Lên là lên luôn cùng những bản nhạc",
  },
];

function App() {
  const [show, setShow] = useState(false);

  return (
    <div className="container">
      <Header
        data={userdata}
        info="this is infomation"
        newdata="newData"
        data2={phone}
        data60User={newData}
      />
      {/* <NewTest /> */}
      {/* <ChangeNumber /> */}
      <UseEffectFeature />
      <button className="btn btn-primary" onClick={() => setShow(!show)}>
        Show or Hidden
      </button>
      {show && <TodoListVersion1 />}

      <ShowSongs
        dataOfSongs={zingMp3Data}
        dataofSongs2={zingMp3Data2}
        run={false}
      />
    </div>
  );
}

export default App;
